let projects = [
    {
        id: 1,
        name: "STUDIO BOOKS",
        description: "ART DIRECTION AND PHOTOGRAPHY",
        type: "image",
        path: "../assets/images/min/DSCF5112 2.jpg",
    },
    {
        id: 2,
        name: "MATILDE CASHMERE",
        description: "IDENTITY, CORPORATE HANGTAGS. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "big-image",
        path: "../assets/images/min/etiqueta2.jpg",
    },
    {
        id: 3,
        name: "MAGÓKORO",
        description: "BOOK (INSIDE), FLAVIA COMPANY’S NOVEL, GRAPHIC DESIGN. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "image",
        path: "../assets/images/min/Magokoro-2.jpg",
    },
    {
        id: 4,
        name: "MAGÓKORO",
        description: "BOOK (INSIDE), FLAVIA COMPANY’S NOVEL, GRAPHIC DESIGN. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "image",
        path: "../assets/images/min/9788416673759.jpg",
    },
    {
        id: 5,
        name: "AUKA CONCEPT",
        description: "IDENTITY, CAPSULE HANGTAGS. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "image",
        path: "../assets/images/min/Bodego_1.jpg",
    },
    {
        id: 6,
        name: "AUKA CONCEPT",
        description: "IDENTITY, CAPSULE HANGTAGS. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "image",
        path: "../assets/images/min/bolsa_auka2_1.jpg",
    },
    {
        id: 7,
        name: "UN COLCHÓN PARA RAEL",
        description: "MOVIE SALE DOSIER, GRAPHIC DESIGN. DESIGNED IN MIRINDA COMPANY STUDIO",
        type: "video",
        path: "../assets/videos/colchonpararael_animacio.mp4",
    },
]